### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by bio-boris** [kbase/JobRunner#2]
### General Issues
* Cannot run unit tests (test_jobrunner.py) (test_methodrunner.py)

### jobrunner.py

* Looks good
* Suggestion: Maybe check to see if all services are up (catalog/njs/shock/auth) before running the job. Maybe timeout waiting for services to start?

### JobRunner.py
* TODO Fix Cgroup function
* Should emit condor job id (os.environ.get(CONDOR_ID))
* ~~Should be able to run job if job is not COMPLETED or ERROR  (njs.check_job_canceled.finished might be doing this already)~~ 
* When removing container, you need to pass in the 'v' parameter to remove volumes associated with the container. IIRC You also need to kill any running containers before removing them. (Currently just `c.remove() is insufficient)
* Address various TODOS in the file

### CatalogCache.py 
* Looks good

### provenance.py 
* Looks good

### logger.py  
* You can import logging and do logging.info instead of print
* You should cache log lines and send multiple instead of sending them every time we have one line. The current sdklmr sends them every 1 second. Or we can wait till there are N number of elements in the array

### Methodrunner.py
* Does the context dictionary need to be properly filled out?
```
   if (context.getCallStack() == null)
                context.setCallStack(new ArrayList<MethodCall>());
            context.getCallStack().add(new MethodCall().withJobId(jobId).withMethod(job.getMethod())
                    .withTime(DATE_FORMATTER.print(new DateTime())));
```
* Lacking ability to specify requestedRelease

### Provenance
* Looks good. Might want to check to make sure value is in dictionary or setting defaults for service_ver or method_params

### DockerRunner
* Very cool shepherd function
* I think pulling the docker image is not necessary, I think you can just run it without downloading but maybe its faster  or more reliable to do it manually?
* Cleanup function remove is a function call I believe, not an attribute

### CallbackServer
* Looks good. 
* Missing status()
* Unclear about how it handle subsequent jobs.. It adds them to the queue?
* Max 10 jobs limit is missing?
* Can it handle different versions of the same module?
* Should it keep its own log?

**Comment by scanon** [comment]
**General**
See if you can run in the offline tests.  I still need to rework the online to work for any user.
nosetests -a offline

**jobrunner**

- [ ] Suggestion: Maybe check to see if all services are up (catalog/njs/shock/auth) before running the job. Maybe timeout waiting for services to start? - I think we just need to add retries with some limit.

**JobRunner.py**
- [x] TODO Fix Cgroup function - Done

Should emit condor job id (os.environ.get(CONDOR_ID)) - Just print the Job ID?

Should be able to run job if job is not COMPLETED or ERROR (njs.check_job_canceled.finished might be doing this already) - I don't follow

When removing container, you need to pass in the 'v' parameter to remove volumes associated with the container. IIRC You also need to kill any running containers before removing them. (Currently just `c.remove() is insufficient) - We should check this

Address various TODOS in the file - I've done some of these.

**logger.py**
You can import logging and do logging.info instead of print - I've changed the prints to a debug option.

You should cache log lines and send multiple instead of sending them every time we have one line. The current sdklmr sends them every 1 second. Or we can wait till there are N number of elements in the array - Good point.  Added todo

**Methodrunner.py**

- [ ] Does the context dictionary need to be properly filled out? - Added todo but need to check how it is used.
- [ ] Lacking ability to specify requestedRelease - I think this is fixed but we should confirm.

**Provenance**
Looks good. Might want to check to make sure value is in dictionary or setting defaults for service_ver or method_params - I think it is okay but should confirm

**DockerRunner**
- [ ] I think pulling the docker image is not necessary, I think you can just run it without downloading but maybe its faster or more reliable to do it manually? - I think this is fine.
- [x] Cleanup function remove is a function call I believe, not an attribute

**CallbackServer**

- [ ] Missing status() - Do you know how this is called?
- [x] Unclear about how it handle subsequent jobs.. It adds them to the queue? - Yes
- [x] Max 10 jobs limit is missing?

Can it handle different versions of the same module? I don't think so.  Sanic does emit a log though.
Can it handle different versions of the same module? We don't allow this

**Comment by bio-boris** [comment]
RE: Volumes
So actually what is going on is removing the volumes associated with the container, not actually deleting the volumes, so nevermind on that point. This step is required in case you want to delete the container, and you cannot because a volume is associated with it.
